# Generated by Django 3.0.7 on 2020-12-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20201226_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_no',
            field=models.IntegerField(),
        ),
    ]
