# Generated by Django 3.0.7 on 2020-12-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201226_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='vin_no',
        ),
    ]
