# Generated by Django 3.0.7 on 2020-12-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_car_vin_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vin_no',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
